version: '3'
services:
  tachyon-fake:
    build:
      context: ../
      dockerfile: testcase/tachyonfake/Dockerfile
    ports:
      - "8084:8084"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8084/health"]
      interval: 1s
      timeout: 1s
      retries: 5
      start_period: 1s

  recoil-autohost:
    build:
      context: ../
      dockerfile: testcase/autohost/Dockerfile
    volumes:
      - ../config.dev.json:/app/config.json:ro
      - ./test_logs:/app/logs
    ports:
      - "20000-21000:20000-21000"
      - "22000-23000:22000-23000"
    environment:
      - TINI_SUBREAPER=true
    command: ["node", "dist/main.js", "/app/config.json"]
    depends_on:
      tachyon-fake:
        condition: service_healthy

networks:
  autohost-network:
    driver: bridge 